PFCSYN/WebApplication1/Models/Domain/Message.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models.Domain
{
    public class Message
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid MessageId { get; set; }
        public string Messagetxt { get; set; }

        public string Content { get; set; }
    }
}

PFCSYN/WebApplication1/Models/ErrorViewModel.cs
using System;

namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PFCSYN/WebApplication1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PFCSYN/WebApplication1/Controllers/MessagesController.cs
using Google.Cloud.Storage.V1;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.DataAccess.Interfaces;
using WebApplication1.Models.Domain;

namespace WebApplication1.Controllers
{
    public class MessagesController : Controller
    {
        private readonly IMessagesRepository _messagesRepo;
        private readonly IConfiguration _config;
        private readonly IPubSubRepository _pubsubRepo;

        public MessagesController(IMessagesRepository messagesRepo, IConfiguration config, IPubSubRepository pubsubRepo)
        {
            _config = config;
            _messagesRepo = messagesRepo;
            _pubsubRepo = pubsubRepo;
        }
        public IActionResult Index()
        {
            var list = _messagesRepo.GetMessages();
            return View(list);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Create(IFormFile atch, Message m)
        {
            string bucketName = _config.GetSection("AppSettings").GetSection("BucketName").Value;
            string uniqueFilename = Guid.NewGuid() + System.IO.Path.GetExtension(atch.FileName);

            var storage = StorageClient.Create();

            using (var myStream = atch.OpenReadStream())
            {
                storage.UploadObject(bucketName, uniqueFilename, null, myStream);
            }

            m.Content = $"https://storage.googleapis.com/{bucketName}/{uniqueFilename}";

            _messagesRepo.AddMessage(m);

            //publishmessage
            string emailRecipient = HttpContext.User.Identity.Name; //the email of the current logged user
            _pubsubRepo.PublishMessage(m, emailRecipient);

            return RedirectToAction("Index");           
        }

        public IActionResult Fetch()
        {
            string msgSerialized = _pubsubRepo.PullMessage();
            if (msgSerialized == string.Empty) return Content("No message read");
            dynamic myDeserializedData = JsonConvert.DeserializeObject(msgSerialized);
            string email = myDeserializedData.Email;
            string messageText = myDeserializedData.Message.Messagetxt;
            string contentUrl = myDeserializedData.Message.Content;

            /*email = User.Identity.Name;
            messageText = */


            //return View();
            return Content("Message received");
        }
    }
}

PFCSYN/WebApplication1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PFCSYN/WebApplication1/Views/Messages/Create.cshtml
@model WebApplication1.Models.Domain.Message

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Message</h4>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label class="control-label">Message</label>
                <input asp-for="Messagetxt" class="form-control" />
                <span asp-validation-for="Messagetxt" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">Attach A File</label>
                <input type="file" name="atch" class="form-control" />

            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PFCSYN/WebApplication1/Views/Messages/Fetch.cshtml
@model IEnumerable<WebApplication1.Models.Domain.Message>

@{
    ViewData["Title"] = "Fetch";
}

<h1>Fetch</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Messagetxt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Content)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Messagetxt)
            </td>
            <td>
                <img src="@item.Content" style="width:230px;height:150px" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Content)
            </td>
        </tr>
}
    </tbody>
</table>

PFCSYN/WebApplication1/Views/Messages/Index.cshtml
@model IEnumerable<WebApplication1.Models.Domain.Message>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Messagetxt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Content)
            </th>
            <th>
                URL
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Messagetxt)
            </td>
            <td>
                <img src="@item.Content" style="width:230px;height:150px" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Content)
            </td>
        </tr>
}
    </tbody>
</table>

PFCSYN/WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Messages" asp-action="Index">Messages</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Messages" asp-action="Create">Create Message</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Messages" asp-action="Fetch">Fetch Message</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>